# LOCAL

## 1.Gerekli Kütüphanelerin Kurulumu

In [51]:
import numpy as np

listex = ["-","G","C","A","G","A","G","C","A","C","G"]
listey = ["-","G","C","T","G","G","A","A","G","G","C","A","T"]
x=1
y=1
gap = -4
match = 5
mismatch = -4

listex = ["-","K","V","L","E","F","G","Y"]
listey = ["-","E","Q","L","L","K","A","L","E","F","K","L"]
x=1
y=1
gap = -1
match = 4
mismatch = -2

## 2.Sayılar ile Matrisin oluşturulması ve Değer Atamaları

In [ ]:
listex = list(input("yukarıdan aşağı:"))
listex = ["-"] + listex
listey = list(input("saoldan sağa:"))
listey = ["-"] + listey
x=1
y=1
gap = int(input("gap:"))
alınangap = gap
match = int(input("match:"))
mismatch = int(input("mismatch:"))
a = np.zeros((len(listex),len(listey)))
a = a.astype(int)
l1 = []
l2 = []

* KVLEFGY
* EQLLKALEFKL
* -1
* 4
* -2

In [40]:
x=1
y=1
a = np.zeros((len(listex),len(listey)))
a = a.astype(int)
l1 = []
l2 = []

In [41]:
a

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [42]:
while x<len(listex):
    while y<len(listey):
        if listex[x] == listey[y]:
            a[x,y] = max(a[x-1,y-1] + match,a[x-1,y] + gap, a[x,y-1] + gap)
        else:
            a[x,y] = max(a[x-1,y-1] + mismatch,a[x-1,y] + gap, a[x,y-1] + gap,0)
        y+=1
    y=1
    x+=1

In [43]:
a

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  4,  0,  0,  0,  0,  4,  0],
       [ 0,  0,  0,  0,  0,  0,  2,  0,  0,  0,  0,  2],
       [ 0,  0,  0,  4,  4,  0,  0,  6,  1,  0,  0,  4],
       [ 0,  4,  0,  0,  2,  2,  0,  1, 10,  5,  0,  0],
       [ 0,  0,  2,  0,  0,  0,  0,  0,  5, 14,  9,  4],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  9, 12,  7],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  4,  7, 10]])

### 2.5 Matristeki En Yüksek Değeri Bulunması

In [44]:
result = np.where(a == np.max(a))
lst = list(zip(result[0],result[1]))
g1 =  lst[0][0]
h1 =  lst[0][1]
#g2 = deneme[max(list(deneme.keys()))][0]
#h2 = deneme[max(list(deneme.keys()))][1]

In [45]:
g1,h1

(5, 9)

## 3.Harf ile Hizalama İşlemleri

In [46]:
print("İlerleyiş")
print(g1,h1)
while g1>0 and h1>0:
    if a[g1-1,h1] == a[g1,h1] - gap :
        g1-=1
        l2.append(listex[g1+1])
        l1.append("_")
    elif a[g1,h1-1]  == a[g1,h1] - gap:
        h1-=1
        print(g1,h1)
        l2.append("_")
        l1.append(listey[h1+1])
    elif a[g1-1,h1-1] == a[g1,h1] - match:
        g1-=1
        h1-=1
        print(g1,h1)
        l1.append(listex[g1+1])
        l2.append(listey[h1+1])
    elif a[g1-1,h1-1]  == a[g1,h1] - mismatch:
        g1-=1
        h1-=1
        print(g1,h1)
        l2.append(listex[g1+1])
        l1.append(listey[h1+1])

İlerleyiş
5 9
4 8
3 7
2 6
1 5
0 4


In [47]:
l1.reverse()
l2.reverse()
print(l1)
print(l2)

['K', 'A', 'L', 'E', 'F']
['K', 'V', 'L', 'E', 'F']


In [17]:
print("İlerleyiş")
print(g1,h1)
while g1>0 and h1>0:
    
    if a[g1,h1-1]  == a[g1,h1] - gap:
        h1-=1
        print(g1,h1)
        l2.append("_")
        l1.append(listey[h1+1])
    elif a[g1-1,h1] == a[g1,h1] - gap :
        g1-=1
        l2.append(listex[g1+1])
        l1.append("_")
    elif a[g1-1,h1-1] == a[g1,h1] - match:
        g1-=1
        h1-=1
        print(g1,h1)
        l1.append(listex[g1+1])
        l2.append(listey[h1+1])
    elif a[g1-1,h1-1]  == a[g1,h1] - mismatch:
        g1-=1
        h1-=1
        print(g1,h1)
        l2.append(listex[g1+1])
        l1.append(listey[h1+1])

İlerleyiş
5 9
4 8
3 7
2 6
2 5
0 4


In [18]:
l1.reverse()
l2.reverse()
print(l1)
print(l2)

['K', '_', 'A', 'L', 'E', 'F']
['K', 'V', '_', 'L', 'E', 'F']


# GLOBAL

## 1.Blosum Matrisi Atama ve Kütüphaneler

In [48]:
import numpy as np
blosum62 = {
    ('W', 'F'): 1, ('L', 'R'): -2, ('S', 'P'): -1, ('V', 'T'): 0,
    ('Q', 'Q'): 5, ('N', 'A'): -2, ('Z', 'Y'): -2, ('W', 'R'): -3,
    ('Q', 'A'): -1, ('S', 'D'): 0, ('H', 'H'): 8, ('S', 'H'): -1,
    ('H', 'D'): -1, ('L', 'N'): -3, ('W', 'A'): -3, ('Y', 'M'): -1,
    ('G', 'R'): -2, ('Y', 'I'): -1, ('Y', 'E'): -2, ('B', 'Y'): -3,
    ('Y', 'A'): -2, ('V', 'D'): -3, ('B', 'S'): 0, ('Y', 'Y'): 7,
    ('G', 'N'): 0, ('E', 'C'): -4, ('Y', 'Q'): -1, ('Z', 'Z'): 4,
    ('V', 'A'): 0, ('C', 'C'): 9, ('M', 'R'): -1, ('V', 'E'): -2,
    ('T', 'N'): 0, ('P', 'P'): 7, ('V', 'I'): 3, ('V', 'S'): -2,
    ('Z', 'P'): -1, ('V', 'M'): 1, ('T', 'F'): -2, ('V', 'Q'): -2,
    ('K', 'K'): 5, ('P', 'D'): -1, ('I', 'H'): -3, ('I', 'D'): -3,
    ('T', 'R'): -1, ('P', 'L'): -3, ('K', 'G'): -2, ('M', 'N'): -2,
    ('P', 'H'): -2, ('F', 'Q'): -3, ('Z', 'G'): -2, ('X', 'L'): -1,
    ('T', 'M'): -1, ('Z', 'C'): -3, ('X', 'H'): -1, ('D', 'R'): -2,
    ('B', 'W'): -4, ('X', 'D'): -1, ('Z', 'K'): 1, ('F', 'A'): -2,
    ('Z', 'W'): -3, ('F', 'E'): -3, ('D', 'N'): 1, ('B', 'K'): 0,
    ('X', 'X'): -1, ('F', 'I'): 0, ('B', 'G'): -1, ('X', 'T'): 0,
    ('F', 'M'): 0, ('B', 'C'): -3, ('Z', 'I'): -3, ('Z', 'V'): -2,
    ('S', 'S'): 4, ('L', 'Q'): -2, ('W', 'E'): -3, ('Q', 'R'): 1,
    ('N', 'N'): 6, ('W', 'M'): -1, ('Q', 'C'): -3, ('W', 'I'): -3,
    ('S', 'C'): -1, ('L', 'A'): -1, ('S', 'G'): 0, ('L', 'E'): -3,
    ('W', 'Q'): -2, ('H', 'G'): -2, ('S', 'K'): 0, ('Q', 'N'): 0,
    ('N', 'R'): 0, ('H', 'C'): -3, ('Y', 'N'): -2, ('G', 'Q'): -2,
    ('Y', 'F'): 3, ('C', 'A'): 0, ('V', 'L'): 1, ('G', 'E'): -2,
    ('G', 'A'): 0, ('K', 'R'): 2, ('E', 'D'): 2, ('Y', 'R'): -2,
    ('M', 'Q'): 0, ('T', 'I'): -1, ('C', 'D'): -3, ('V', 'F'): -1,
    ('T', 'A'): 0, ('T', 'P'): -1, ('B', 'P'): -2, ('T', 'E'): -1,
    ('V', 'N'): -3, ('P', 'G'): -2, ('M', 'A'): -1, ('K', 'H'): -1,
    ('V', 'R'): -3, ('P', 'C'): -3, ('M', 'E'): -2, ('K', 'L'): -2,
    ('V', 'V'): 4, ('M', 'I'): 1, ('T', 'Q'): -1, ('I', 'G'): -4,
    ('P', 'K'): -1, ('M', 'M'): 5, ('K', 'D'): -1, ('I', 'C'): -1,
    ('Z', 'D'): 1, ('F', 'R'): -3, ('X', 'K'): -1, ('Q', 'D'): 0,
    ('X', 'G'): -1, ('Z', 'L'): -3, ('X', 'C'): -2, ('Z', 'H'): 0,
    ('B', 'L'): -4, ('B', 'H'): 0, ('F', 'F'): 6, ('X', 'W'): -2,
    ('B', 'D'): 4, ('D', 'A'): -2, ('S', 'L'): -2, ('X', 'S'): 0,
    ('F', 'N'): -3, ('S', 'R'): -1, ('W', 'D'): -4, ('V', 'Y'): -1,
    ('W', 'L'): -2, ('H', 'R'): 0, ('W', 'H'): -2, ('H', 'N'): 1,
    ('W', 'T'): -2, ('T', 'T'): 5, ('S', 'F'): -2, ('W', 'P'): -4,
    ('L', 'D'): -4, ('B', 'I'): -3, ('L', 'H'): -3, ('S', 'N'): 1,
    ('B', 'T'): -1, ('L', 'L'): 4, ('Y', 'K'): -2, ('E', 'Q'): 2,
    ('Y', 'G'): -3, ('Z', 'S'): 0, ('Y', 'C'): -2, ('G', 'D'): -1,
    ('B', 'V'): -3, ('E', 'A'): -1, ('Y', 'W'): 2, ('E', 'E'): 5,
    ('Y', 'S'): -2, ('C', 'N'): -3, ('V', 'C'): -1, ('T', 'H'): -2,
    ('P', 'R'): -2, ('V', 'G'): -3, ('T', 'L'): -1, ('V', 'K'): -2,
    ('K', 'Q'): 1, ('R', 'A'): -1, ('I', 'R'): -3, ('T', 'D'): -1,
    ('P', 'F'): -4, ('I', 'N'): -3, ('K', 'I'): -3, ('M', 'D'): -3,
    ('V', 'W'): -3, ('W', 'W'): 11, ('M', 'H'): -2, ('P', 'N'): -2,
    ('K', 'A'): -1, ('M', 'L'): 2, ('K', 'E'): 1, ('Z', 'E'): 4,
    ('X', 'N'): -1, ('Z', 'A'): -1, ('Z', 'M'): -1, ('X', 'F'): -1,
    ('K', 'C'): -3, ('B', 'Q'): 0, ('X', 'B'): -1, ('B', 'M'): -3,
    ('F', 'C'): -2, ('Z', 'Q'): 3, ('X', 'Z'): -1, ('F', 'G'): -3,
    ('B', 'E'): 1, ('X', 'V'): -1, ('F', 'K'): -3, ('B', 'A'): -2,
    ('X', 'R'): -1, ('D', 'D'): 6, ('W', 'G'): -2, ('Z', 'F'): -3,
    ('S', 'Q'): 0, ('W', 'C'): -2, ('W', 'K'): -3, ('H', 'Q'): 0,
    ('L', 'C'): -1, ('W', 'N'): -4, ('S', 'A'): 1, ('L', 'G'): -4,
    ('W', 'S'): -3, ('S', 'E'): 0, ('H', 'E'): 0, ('S', 'I'): -2,
    ('H', 'A'): -2, ('S', 'M'): -1, ('Y', 'L'): -1, ('Y', 'H'): 2,
    ('Y', 'D'): -3, ('E', 'R'): 0, ('X', 'P'): -2, ('G', 'G'): 6,
    ('G', 'C'): -3, ('E', 'N'): 0, ('Y', 'T'): -2, ('Y', 'P'): -3,
    ('T', 'K'): -1, ('A', 'A'): 4, ('P', 'Q'): -1, ('T', 'C'): -1,
    ('V', 'H'): -3, ('T', 'G'): -2, ('I', 'Q'): -3, ('Z', 'T'): -1,
    ('C', 'R'): -3, ('V', 'P'): -2, ('P', 'E'): -1, ('M', 'C'): -1,
    ('K', 'N'): 0, ('I', 'I'): 4, ('P', 'A'): -1, ('M', 'G'): -3,
    ('T', 'S'): 1, ('I', 'E'): -3, ('P', 'M'): -2, ('M', 'K'): -1,
    ('I', 'A'): -1, ('P', 'I'): -3, ('R', 'R'): 5, ('X', 'M'): -1,
    ('L', 'I'): 2, ('X', 'I'): -1, ('Z', 'B'): 1, ('X', 'E'): -1,
    ('Z', 'N'): 0, ('X', 'A'): 0, ('B', 'R'): -1, ('B', 'N'): 3,
    ('F', 'D'): -3, ('X', 'Y'): -1, ('Z', 'R'): 0, ('F', 'H'): -1,
    ('B', 'F'): -3, ('F', 'L'): 0, ('X', 'Q'): -1, ('B', 'B'): 4 ,
("N","D"): 1,('A', 'D'):-2,('A', 'S'):1,('A', 'E'):-1,('A', 'N'):-2,('N', 'S'):1,('N', 'E'):0,('D', 'S'):0,('D', 'E'):2
,('D', 'L'):-4,('A', 'L'):-1,('E', 'L'):-3}

In [50]:
x=0
y=0
b = np.zeros((len(listex),len(listey)))
b = b.astype(int)
gap = 0
alınangap=int(input("gap:"))
while y < len(listex)-1:
        b[x,y] = gap
        gap+=alınangap
        y+=1
x=0
y=0
gap=0
while x < len(listey)+1:
        b[x,y] = gap
        gap+=alınangap
        x+=1
x=1
y=1
gap=0
l1 = []
l2 = []

gap:-5


IndexError: index 8 is out of bounds for axis 0 with size 8

listex = list(input("listex:"))
listex = ["-"] + listex
listey = list(input("listey:"))
listey = ["-"] + listey
x=0
y=0
b = np.zeros((len(listex),len(listey)))
b = b.astype(int)
gap = 0
while y < len(listex)-1:
        b[x,y] = gap
        gap-=int(input("gap:"))
        y+=1
x=0
y=0
gap=0
while x < len(listey)+1:
        b[x,y] = gap
        gap-=int(input("gap:"))
        x+=1
x=1
y=1
gap=0
l1 = []
l2 = []

listex = ["-","S","E","N","D"]
listey = ["-","A","N","D"]
x=0
y=0
match = "bLOSAM"
b = np.zeros((len(listex),len(listey)))
b = b.astype(int)
deger=0

## 2.Sayı Matrisini Oluşturma

In [32]:
listex = ["-","A","A","E","L","L"]
listey = ["-","D","A","E","E"]
x=0
y=0
b = np.zeros((len(listex),len(listey)))
b = b.astype(int)
deger=0
while y < len(listex)-1:
        b[x,y] = deger
        deger-=5
        y+=1
x=0
y=0
deger=0
while x < len(listey)+1:
        b[x,y] = deger
        deger-=5
        x+=1
x=1
y=1
deger=0
l1 = []
l2 = []

while y < len(listex)-1:
        b[x,y] = deger
        deger-=10
        y+=1
x=0
y=0
deger=0
while x < len(listey)+1:
        b[x,y] = deger
        deger-=10
        x+=1
x=1
y=1
deger=0
l1 = []
l2 = []

In [33]:
b = b.T

In [34]:
b

array([[  0,  -5, -10, -15, -20, -25],
       [ -5,   0,   0,   0,   0,   0],
       [-10,   0,   0,   0,   0,   0],
       [-15,   0,   0,   0,   0,   0],
       [-20,   0,   0,   0,   0,   0]])

### 2.5 Sayı Matrisine Atamalar

In [35]:
deger = -5
while x < len(listey):
    while y < len(listex):
        b[x,y] = max(b[x-1,y-1] + blosum62[listey[x],listex[y]] ,b[x-1,y] + deger, b[x,y-1] + deger)
        y+=1
    y=1
    x+=1

In [36]:
b

array([[  0,  -5, -10, -15, -20, -25],
       [ -5,  -2,  -7,  -8, -13, -18],
       [-10,  -1,   2,  -3,  -8, -13],
       [-15,  -6,  -2,   7,   2,  -3],
       [-20, -11,  -7,   3,   4,  -1]])

## 3.Harflerin Yerleştirilmesi

In [35]:
g1 = len(listey)-1
h1 = len(listex)-1

In [36]:
cık = -5

In [37]:
print("İlerleyiş")
print(g1,h1)
while g1>0 and h1>0:
    if b[g1-1,h1] == b[g1,h1] - cık :
        g1-=1
        print(g1,h1)
        l1.append("_")
        l2.append(listey[g1+1])
    elif b[g1,h1-1]  == b[g1,h1] - cık:
        h1-=1
        print(g1,h1)
        l1.append(listex[h1+1])
        l2.append("_")
    elif b[g1-1,h1-1] == b[g1,h1] - blosum62[listey[g1],listex[h1]]:
        g1-=1
        h1-=1
        print(g1,h1)
        l2.append(listey[g1+1])
        l1.append(listex[h1+1])
   


İlerleyiş
4 5
4 4
3 3
2 2
1 1
0 0


In [ ]:
l1.reverse()
l2.reverse()

print(l1)
print(l2)

In [38]:
print("İlerleyiş")
print(g1,h1)
while g1>0 and h1>0:
    if b[g1-1,h1-1] == b[g1,h1] - blosum62[listey[g1],listex[h1]]:
        g1-=1
        h1-=1
        print(g1,h1)
        l2.append(listey[g1+1])
        l1.append(listex[h1+1])
    elif b[g1-1,h1] == b[g1,h1] - cık :
        g1-=1
        print(g1,h1)
        l1.append("_")
        l2.append(listey[g1+1])
    elif b[g1,h1-1]  == b[g1,h1] - cık:
        h1-=1
        print(g1,h1)
        l1.append(listex[h1+1])
        l2.append("_")


İlerleyiş
0 0


In [20]:
l1.reverse()
l2.reverse()

print(l1)
print(l2)

['A', 'A', 'E', 'L', 'L']
['D', 'A', 'E', '_', 'E']


In [39]:
print("İlerleyiş")
print(g1,h1)
while g1>0 and h1>0:
    if b[g1-1,h1] == b[g1,h1] - cık :
        g1-=1
        print(g1,h1)
        l1.append("_")
        l2.append(listey[g1+1])
    elif b[g1,h1-1]  == b[g1,h1] - cık:
        h1-=1
        print(g1,h1)
        l1.append(listex[h1+1])
        l2.append("_")
    elif b[g1-1,h1-1] == b[g1,h1] - blosum62[listey[g1],listex[h1]]:
            g1-=1
            h1-=1
            print(g1,h1)
            l2.append(listey[g1+1])
            l1.append(listex[h1+1])

İlerleyiş
4 5
4 4
3 3
2 2
1 1
0 0


In [40]:
l1.reverse()
l2.reverse()

print(l1)
print(l2)

['A', 'A', 'E', 'L', 'L']
['D', 'A', 'E', 'E', '_']
